# Docker-compose file for
# Basicstation Protokoll for a TTN gateway
# Collectd reporting stack
# Requires docker-compose 1.9 or newer

# Version 2.1 for resin compatibility
version: '2.1'
services:
  # Gateway Basicstation protokoll
  gateway:
    build: gateway
    image: dasdigidings/ttn-gateway
    privileged: true
    network_mode: host
    restart: always
    environment:
      GW_GPS: "${GW_GPS:-false}"
      GW_RESET_PIN: "${GW_RESET_PIN:-11}"
      GW_RESET_GPIO: "${GW_RESET_GPIO:-17}"
      MODEL: "${MODEL:-SX1301}"
      TTN_STACK_VERSION: "${TTN_STACK_VERSION:-3}"
      TTN_REGION: "${TTN_REGION:-eu1}"
      TC_KEY: "${TC_KEY:-0}"
    volumes:
      - var_ttn_vol:/var/ttn
  # Collectd
  collectd:
    build: collectd
    image: dasdigidings/ttn-collectd
    privileged: true
    network_mode: host
    restart: always
    environment:
      GW_COLLECTD_SERVER: "${GW_COLLECTD_SERVER}"
      GW_COLLECTD_INTERVAL: "${GW_COLLECTD_INTERVAL}"
      GW_BME280: "${GW_BME280:-false}"
      GW_BME280_ADDR: "${GW_BME280_ADDR}"
      GW_BME280_SMBUS: "${GW_BME280_SMBUS}"
    volumes:
      - var_ttn_vol:/var/ttn

volumes:
  var_ttn_vol:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs